spring:
  application:
    name: ecar-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecardb # postgres sql url
    username: postgres # postgres username
    password: 12345 # postgres password
    # config thread-pool
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 25
  # jpa config
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # show sql
    hibernate:
      ddl-auto: update # create, create-drop, update, validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 440436287911-ma1vpnb0h721a3d8agij4re1ferh53ii.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email

  # Cấu hình gửi mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: lengochan090105@gmail.com
    password: pliv pahe tyid jrpz # app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
paypal:
  successUrl: http://localhost:8080/payment/success
  cancelUrl: http://localhost:8080/payment/cancel
  client-id: Ad0ve8-46Llve89fGR4aUhk-4F86DEWWAcZl_73J-vVQxCImtbx7lkmoV65SoigNv_C0G67dSIDMpomG
  client-secret: EEc9slx2Rcw5Fv3karcYq71p0dYlPQqT6gIGuzncthK-j-tZSPj1Vdl4UphiRqT3gk-WWGK-ATlCGMEy
  mode: sandbox
server:
  port: 8080
logging:
  level:
    org.springframework.security: INFO
