spring:
  application:
    name: ecar-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecardb # postgres sql url
    username: postgres # postgres username
    password: postgres # postgres password
    # config thread-pool
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      minimum-idle: 25
  # jpa config
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # show sql
    hibernate:
      ddl-auto: update # update means check if table in entities existed or not, if not -> create new table with
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 945115052613-hu47pope4oc2gn1djuv1srm4ju3rt3bv.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email

  # Cấu hình gửi mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: lengochan090105@gmail.com
    password: pliv pahe tyid jrpz # app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
paypal:
  successUrl: http://localhost:4200/paypal/success
  cancelUrl: http://localhost:4200/paypal/cancel
  client-id: Ad0ve8-46Llve89fGR4aUhk-4F86DEWWAcZl_73J-vVQxCImtbx7lkmoV65SoigNv_C0G67dSIDMpomG
  client-secret: EEc9slx2Rcw5Fv3karcYq71p0dYlPQqT6gIGuzncthK-j-tZSPj1Vdl4UphiRqT3gk-WWGK-ATlCGMEy
  mode: sandbox

server:
  port: 8080
logging:
  level:
    org.springframework.security: INFO
